#![allow(unused_imports)]
use soroban_sdk::{contracterror, contracttype, Address, Bytes, String, Vec};

#[contracterror]
#[derive(Copy, Clone, Debug, Eq, PartialEq, PartialOrd, Ord)]
#[repr(u32)]
pub enum ContractError {
    AlreadyInitialized = 1,
    NotInitialized = 2,
    InvalidInput = 3,
    InvalidAgentId = 4,
    LimitExceeded = 5,
    NotReady = 6,
    InternalError = 7,
    Unauthorized = 100,
    RoleEscalationAttempt = 102,
    RoleConflict = 103,
    InvalidMetadata = 403,
    MetadataTooLong = 404,
    CapabilitiesExceeded = 405,
    KycRequestExpired = 504,
    KycSubjectNotFound = 800,
    KycInvalidTransition = 801,
    KycTerminalState = 802,
    ComplianceCheckFailed = 803,
    KycNotVerified = 21,
    KycOverrideNotScheduled = 22,
    KycOverrideNotReady = 23,
    KycOverrideAlreadyScheduled = 24,
    // Agent and NFT errors
    AgentNotFound = 30,
    OverflowError = 31,
    InvalidRoyaltyFee = 32,
    DuplicateAgentId = 33,
    AgentLeased = 34,
    NotOwner = 35,
    SameAddressTransfer = 36,
    NotFound = 37,
    AlreadyExists = 38,
    // AMM integration errors (Issue #245)
    AmmNotConfigured = 50,
    TokenNotAccepted = 51,
    InsufficientSwapOutput = 52,
    SwapFailed = 53,
}

pub fn error_description(error: ContractError) -> &'static str {
    match error {
        ContractError::AlreadyInitialized => "Already initialized",
        ContractError::NotInitialized => "Not initialized",
        ContractError::InvalidInput => "Invalid input",
        ContractError::InvalidAgentId => "Invalid agent ID",
        ContractError::LimitExceeded => "Limit exceeded",
        ContractError::NotReady => "Not ready or window not elapsed",
        ContractError::InternalError => "Internal error",
        ContractError::Unauthorized => "Unauthorized",
        ContractError::RoleEscalationAttempt => "Role escalation",
        ContractError::RoleConflict => "Role conflict",
        ContractError::InvalidMetadata => "Invalid metadata",
        ContractError::MetadataTooLong => "Metadata too long",
        ContractError::CapabilitiesExceeded => "Capabilities exceeded",
        ContractError::KycRequestExpired => "KYC expired",
        ContractError::KycSubjectNotFound => "KYC subject not found",
        ContractError::KycInvalidTransition => "Invalid KYC transition",
        ContractError::KycTerminalState => "KYC terminal state",
        ContractError::ComplianceCheckFailed => "Compliance check failed",
        ContractError::KycNotVerified => "KYC not verified",
        ContractError::KycOverrideNotScheduled => "KYC override not scheduled",
        ContractError::KycOverrideNotReady => "KYC override not ready",
        ContractError::KycOverrideAlreadyScheduled => "KYC override already scheduled",
        ContractError::AgentNotFound => "Agent not found",
        ContractError::OverflowError => "Arithmetic overflow",
        ContractError::InvalidRoyaltyFee => "Invalid royalty fee",
        ContractError::DuplicateAgentId => "Duplicate agent ID",
        ContractError::AgentLeased => "Agent is currently leased",
        ContractError::NotOwner => "Not the owner",
        ContractError::SameAddressTransfer => "Transfer to same address",
        ContractError::NotFound => "Resource not found",
        ContractError::AlreadyExists => "Resource already exists",
        ContractError::AmmNotConfigured => "AMM contract not configured",
        ContractError::TokenNotAccepted => "Payment token not in accepted list",
        ContractError::InsufficientSwapOutput => "AMM swap output below required amount",
        ContractError::SwapFailed => "AMM swap failed",
    }
}
